manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: davidphilipbarr
      revision: cradio-v2
      import: app/west.yml
  self:
    path: config
